server {
  bind_address = "0.0.0.0"
  bind_port = 8081
  trust_domain = "scotiabank.local"

  data_dir = "/run/spire"

  ca_ttl = "60m"
  default_x509_svid_ttl = "300s"

  log_level = "DEBUG"
}

plugins {
  DataStore "sql" {
    plugin_data {
      database_type = "postgres"
      connection_string = "host=postgres port=5432 user=spire password=spire dbname=spire sslmode=disable connect_timeout=5"
    }
  }

  KeyManager "disk" {
    plugin_data {
      keys_path = "/run/spire/keys.json"
    }
  }

  NodeAttestor "join_token" {
    plugin_data {}
  }


  UpstreamAuthority "disk" {
    plugin_data {
      cert_file_path = "/opt/spire/conf/upstream/intermediate.cert.pem"
      key_file_path  = "/opt/spire/conf/upstream/intermediate.key.pem"
      bundle_path    = "/opt/spire/conf/upstream/root.cert.pem"
    }
  }

}
